nav:
  - index.md
  - 快速入门: 
    - index.md
    - 井字棋: quickstart/tic-tac-toe.md
    - React 哲学: quickstart/thinking-in-react.md
  - 安装:
    - installation/index.md
    - 启动一个新的 React 项目: installation/start-a-new-react-project.md
    - 将 React 添加到现有项目中: installation/add-react-to-an-existing-project.md
    - 使用 TypeScript: installation/use-typescript.md
  
  - 描述UI:
    - describing-ui/index.md
    - 你的第一个组件: describing-ui/your-first-component.md
    - 组件的导入与导出: describing-ui/importing-and-exporting-components.md
    - 使用JSX书写标签语言: describing-ui/writing-markup-with-jsx.md
    - 在JSX中通过大括号使用JavaScript: describing-ui/javascript-in-jsx-with-curly-braces.md
    - 将Props传递给组件: describing-ui/passing-props-to-a-component.md
    - 条件渲染: describing-ui/conditional-rendering.md
    - 渲染列表: describing-ui/rendering-lists.md
    - 保持组件纯粹: describing-ui/keeping-components-pure.md
    - 将UI视作树: describing-ui/understanding-your-ui-as-a-tree.md

  - 添加交互:
      - adding-interactivity/index.md
      - 响应事件: adding-interactivity/responding-to-events.md
      - 组件的内存: adding-interactivity/state-a-components-memory.md
      - 渲染和提交: adding-interactivity/render-and-commit.md
      - 状态快照: adding-interactivity/state-as-a-snapshot.md
      - 队列—系列状态更新: adding-interactivity/queueing-a-series-of-state-updates.md
      - 更新状态中的对象: adding-interactivity/updating-objects-in-state.md
      - 更新状态中的数组: adding-interactivity/updating-arrays-in-state.md

  - 状态管理:
    - managing-state/index.md
    - 使用状态对输入做出反应: managing-state/reacting-to-input-with-state.md
    - 选择状态结构: managing-state/choosing-the-state-structure.md
    - 在组件之间共享状态: managing-state/sharing-state-between-components.md
    - 保留和重置状态: managing-state/preserving-and-resetting-state.md
    - 将状态逻辑提取到Reducer中: managing-state/extracting-state-logic-into-a-reducer.md
    - 使用上下文深入传递数据: managing-state/passing-data-deeply-with-context.md
    - 使用Reducer和上下文进行扩展: managing-state/scaling-up-with-reducer-and-context.md

  - 脱围机制:
    - escape-hatches/index.md
    - 使用引用引用值: escape-hatches/referencing-values-with-refs.md
    - 使用引用操作DOM: escape-hatches/manipulating-the-dom-with-refs.md
    - 使用副作用进行同步: escape-hatches/synchronizing-with-effects.md
    - 你可能不需要副作用: escape-hatches/you-might-not-need-an-effect.md
    - 反应式副作用的生命周期: escape-hatches/lifecycle-of-reactive-effects.md
    - 将事件与副作用分开: escape-hatches/separating-events-from-effects.md
    - 移除副作用依赖: escape-hatches/removing-effect-dependencies.md
    - 使用自定义钩子重用逻辑: escape-hatches/reusing-logic-with-custom-hooks.md

  - 参考:
    - 钩子:
      - reference/hooks/index.md
      - useActionState: reference/hooks/use-action-state.md
      - useCallback: reference/hooks/use-callback.md
      - useContext: reference/hooks/use-context.md
      - useDebugValue: reference/hooks/use-debug-value.md
      - useDeferredValue: reference/hooks/use-deferred-value.md
      - useEffect: reference/hooks/use-effect.md
      - useId: reference/hooks/use-id.md
      - useImperativeHandle: reference/hooks/use-imperative-handle.md
      - useInsertionEffect: reference/hooks/use-insertion-effect.md
      - useLayoutEffect: reference/hooks/use-layout-effect.md
      - useMemo: reference/hooks/use-memo.md
      - useOptimistic: reference/hooks/use-optimistic.md
      - useReducer: reference/hooks/use-reducer.md
      - useRef: reference/hooks/use-ref.md
      - useState: reference/hooks/use-state.md
      - useSyncExternalStore: reference/hooks/use-sync-external-store.md
      - useTransition: reference/hooks/use-transition.md
