nav:
  - React:
  - frontend/react/index.md
  - 快速入门: 
    - frontend/react/index.md
    - 井字棋: frontend/react/quickstart/tic-tac-toe.md
    - React 哲学: frontend/react/quickstart/thinking-in-react.md
  - 安装:
    - frontend/react/installation/index.md
    - 启动一个新的 React 项目: frontend/react/installation/start-a-new-react-project.md
    - 将 React 添加到现有项目中: frontend/react/installation/add-react-to-an-existing-project.md
    - 使用 TypeScript: frontend/react/installation/use-typescript.md
  
  - 描述UI:
    - frontend/react/describing-ui/index.md
    - 你的第一个组件: frontend/react/describing-ui/your-first-component.md
    - 组件的导入与导出: frontend/react/describing-ui/importing-and-exporting-components.md
    - 使用JSX书写标签语言: frontend/react/describing-ui/writing-markup-with-jsx.md
    - 在JSX中通过大括号使用JavaScript: frontend/react/describing-ui/javascript-in-jsx-with-curly-braces.md
    - 将Props传递给组件: frontend/react/describing-ui/passing-props-to-a-component.md
    - 条件渲染: frontend/react/describing-ui/conditional-rendering.md
    - 渲染列表: frontend/react/describing-ui/rendering-lists.md
    - 保持组件纯粹: frontend/react/describing-ui/keeping-components-pure.md
    - 将UI视作树: frontend/react/describing-ui/understanding-your-ui-as-a-tree.md

  - 添加交互:
      - frontend/react/adding-interactivity/index.md
      - 响应事件: frontend/react/adding-interactivity/responding-to-events.md
      - 组件的内存: frontend/react/adding-interactivity/state-a-components-memory.md
      - 渲染和提交: frontend/react/adding-interactivity/render-and-commit.md
      - 状态快照: frontend/react/adding-interactivity/state-as-a-snapshot.md
      - 队列—系列状态更新: frontend/react/adding-interactivity/queueing-a-series-of-state-updates.md
      - 更新状态中的对象: frontend/react/adding-interactivity/updating-objects-in-state.md
      - 更新状态中的数组: frontend/react/adding-interactivity/updating-arrays-in-state.md

  - 状态管理:
    - frontend/react/managing-state/index.md
    - 使用状态对输入做出反应: frontend/react/managing-state/reacting-to-input-with-state.md
    - 选择状态结构: frontend/react/managing-state/choosing-the-state-structure.md
    - 在组件之间共享状态: frontend/react/managing-state/sharing-state-between-components.md
    - 保留和重置状态: frontend/react/managing-state/preserving-and-resetting-state.md
    - 将状态逻辑提取到Reducer中: frontend/react/managing-state/extracting-state-logic-into-a-reducer.md
    - 使用上下文深入传递数据: frontend/react/managing-state/passing-data-deeply-with-context.md
    - 使用Reducer和上下文进行扩展: frontend/react/managing-state/scaling-up-with-reducer-and-context.md

  - 脱围机制:
    - frontend/react/escape-hatches/index.md
    - 使用引用引用值: frontend/react/escape-hatches/referencing-values-with-refs.md
    - 使用引用操作DOM: frontend/react/escape-hatches/manipulating-the-dom-with-refs.md
    - 使用副作用进行同步: frontend/react/escape-hatches/synchronizing-with-effects.md
    - 你可能不需要副作用: frontend/react/escape-hatches/you-might-not-need-an-effect.md
    - 反应式副作用的生命周期: frontend/react/escape-hatches/lifecycle-of-reactive-effects.md
    - 将事件与副作用分开: frontend/react/escape-hatches/separating-events-from-effects.md
    - 移除副作用依赖: frontend/react/escape-hatches/removing-effect-dependencies.md
    - 使用自定义钩子重用逻辑: frontend/react/escape-hatches/reusing-logic-with-custom-hooks.md

  - 参考:
    - 钩子:
      - frontend/react/reference/hooks/index.md
      - useActionState: frontend/react/reference/hooks/use-action-state.md
      - useCallback: frontend/react/reference/hooks/use-callback.md
      - useContext: frontend/react/reference/hooks/use-context.md
      - useDebugValue: frontend/react/reference/hooks/use-debug-value.md
      - useDeferredValue: frontend/react/reference/hooks/use-deferred-value.md
      - useEffect: frontend/react/reference/hooks/use-effect.md
      - useId: frontend/react/reference/hooks/use-id.md
      - useImperativeHandle: frontend/react/reference/hooks/use-imperative-handle.md
      - useInsertionEffect: frontend/react/reference/hooks/use-insertion-effect.md
      - useLayoutEffect: frontend/react/reference/hooks/use-layout-effect.md
      - useMemo: frontend/react/reference/hooks/use-memo.md
      - useOptimistic: frontend/react/reference/hooks/use-optimistic.md
      - useReducer: frontend/react/reference/hooks/use-reducer.md
      - useRef: frontend/react/reference/hooks/use-ref.md
      - useState: frontend/react/reference/hooks/use-state.md
      - useSyncExternalStore: frontend/react/reference/hooks/use-sync-external-store.md
      - useTransition: frontend/react/reference/hooks/use-transition.md
