nav:
  - index.md
  - 1.信用评分基础认识与应用: ch01.md
  - 2.信用评分模型规则与设计: ch02.md
  - 3.分组目的与分析选择: ch03.md
  - 4.细致分析与自变量分析: ch04.md
  - 5.模型建立方法讨论: ch05.md
  - 6.拒绝推论的原因与方法: ch06.md
  - 7.最终模型选择与风险校准: ch07.md
  - 8.决策点设定: ch08.md
  - 9.模型评分模型监控报告: ch09.md
  - 10.信用评分模型策略运用: ch10.md
  - 11.信用评分案例——消费分期: ch11.md
  - 12.信用评分案例——现金贷: ch12.md
  - 13.催收框架: ch13.md
  - 14.催收技巧及KPI标准: ch14.md
