nav:
  - index.md
  - 1.入门指南: ch01.md
  - 2.猜数字游戏: ch02.md
  - 3.通用编程概念: ch03.md
  - 4.认识所有权: ch04.md
  - 5.使用结构体组织相关联的数据: ch05.md
  - 6.枚举和模式匹配: ch06.md
  - 7.使用包、Crate和模块管理不断增长的项目: ch07.md
  - 8.常见集合: ch08.md
  - 9.错误处理: ch09.md
  - 10.泛型类型、特质和生命周期: ch10.md
  - 11.自动化测试: ch11.md
  - 12.IO项目: ch12.md
  - 13.迭代器与闭包: ch13.md
  - 14.认识Cargo和Crates.io: ch14.md
  - 15.智能指针: ch15.md
  - 16.并发: ch16.md
  - 17.面对对象特征: ch17.md
  - 18.模式和匹配: ch18.md
  - 19.高级特征: ch19.md
  - 20.构建多线程Web服务器: ch20.md
  - 21.附录: ch21.md
